language: python

python:
  - 2.6
  - 2.7
  - pypy

script:
  - python pp/test.py

after_success:
  - pip install pep8 pyflakes
  - pep8 pp/*.py
  - pyflakes pp/*.py
  - pep8 *.py
  - pyflakes *.py

matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: pypy
